version: '3'

services:
  bot:
    build: .
    working_dir: /apps
    container_name: aiogram_bot
    env_file:
      - ../nimad/.env
    command: python main.py
    depends_on:
      - pg
  pg:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: 1
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg_data:
